// end-node.jsx — Run-end pseudo-node + special inspector

function EndNode({ x, y, reached = false, selected, onSelect }) {
  return (
    <div className={"end-node" + (reached ? " reached" : "") + (selected ? " selected" : "")}
         style={{ left: x, top: y }}
         onClick={(e) => { e.stopPropagation(); onSelect && onSelect('__end'); }}>
      <span className="en-square"/>
      <span className="node-handle in" style={{position: 'absolute'}}/>
    </div>
  );
}

function EndEdges({ endX, endY, sourceIds, nodes, runningSet }) {
  const NODE_W = 200, NODE_H = 70;
  const tx = endX, ty = endY + 28;
  return (
    <svg style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', pointerEvents: 'none' }}>
      {sourceIds.map((srcId) => {
        const a = nodes.find(n => n.id === srcId);
        if (!a) return null;
        const sx = a.x + NODE_W, sy = a.y + NODE_H / 2;
        const dx = Math.max(40, Math.abs(tx - sx) * 0.5);
        const d = `M ${sx} ${sy} C ${sx + dx} ${sy}, ${tx - dx} ${ty}, ${tx} ${ty}`;
        const active = a.status === 'done';
        return (
          <path key={'ee-' + srcId} d={d}
            stroke={active ? "#10b981" : "#3a414c"}
            strokeWidth="1.5" fill="none" strokeDasharray={active ? "none" : "4 4"}
            markerEnd={active ? "url(#arr-active)" : "url(#arr)"}/>
        );
      })}
    </svg>
  );
}

function EndInspector({ reached = false, terminals = [] }) {
  return (
    <div className="p-body">
      <div className="p-sect" style={{paddingBottom: 10}}>
        <div style={{display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4}}>
          <span style={{
            width: 22, height: 22, borderRadius: 11,
            background: reached ? 'var(--st-done-bg)' : 'var(--bg-3)',
            border: '1px solid ' + (reached ? 'var(--acc-border)' : 'var(--line-strong)'),
            display: 'grid', placeItems: 'center'
          }}>
            <span style={{
              width: 9, height: 9, borderRadius: 2,
              background: reached ? 'var(--st-done)' : 'var(--fg-4)'
            }}/>
          </span>
          <div style={{flex: 1, minWidth: 0}}>
            <div style={{fontSize: 13, fontWeight: 600}}>Run end</div>
            <div style={{fontSize: 11, color: 'var(--fg-3)', marginTop: 2}} className="mono">runtime · pseudo-node</div>
          </div>
          <span className="badge">runtime</span>
        </div>
        <div style={{fontSize: 11, color: 'var(--fg-4)', marginTop: 6, lineHeight: 1.5}}>
          The pipeline halts when any input port receives a value. Mandatory in YAML — generated by the runtime.
        </div>
      </div>

      <div className="p-sect">
        <SectionHead title="Termination reasons" count={terminals.length}/>
        {terminals.map((t, i) => (
          <div key={i} className="port-row">
            <span className={"pdot " + (t.fired ? 'ok' : 'pending')}/>
            <div style={{minWidth: 0}}>
              <div className="pname">{t.port}</div>
              <div className="ppath">{t.fired ? `fired from ${t.from}` : 'pending'}</div>
              {t.reason && <div className="ppath" style={{color: 'var(--fg-3)', marginTop: 4, whiteSpace: 'normal'}}>“{t.reason}”</div>}
            </div>
            <span className="pmeta">{t.fired ? '✓' : '—'}</span>
          </div>
        ))}
      </div>

      <div className="p-sect">
        <SectionHead title="Inputs" count={1}/>
        <div className="port-row">
          <span className={"pdot " + (reached ? 'ok' : 'pending')}/>
          <div style={{minWidth: 0}}>
            <div className="pname">result</div>
            <div className="ppath">accepts: any</div>
          </div>
          <span className="pmeta">{reached ? 'received' : 'waiting'}</span>
        </div>
      </div>
    </div>
  );
}

window.EndNode = EndNode;
window.EndEdges = EndEdges;
window.EndInspector = EndInspector;
